### PR TITLE
Partial italian translation contributed by Raffaele Imperio

### PR DESCRIPTION
**Pull request by lagerspetz**
This should be completed before merging to master.

### CODE REVIEW

**Comment by Raffaele74** [comment]
Well. Wow! I'm very happy for this function. We could do it before! It is easier!
I'm sorry cannot do better.
My Phone finished upload. No Bugs, No Hogs. So I can verify more.
It finished with 113/113 Report delle misure. Counter worked only with 113. It never doesn't work about 6h.
just before end counter works
The counter produces in me the feeling that the literal translation of "Report" can have a different meaning.
I don't understand well what Carat do when it says Updating status so I cannot translate well. Updating is a solution, but If you explane me I can do better. May be "Sto colloquiando con i server"? (I am in contact with servers)
Ugual for some other translations. Here I propose better translation. 
\>> is separator between "as is" and "to be the best I can do now"; 
(xxx): xxx is a comment
Report delle misure >> report delle misure (or better if you explane me)
Updating status >> Updating (or better if you explane me)
Sto finendo >> Sto elaborando (in a few time >> in progress)
Aggiornamento il mio dispositivo >> Aggiornamento del dispositivo (Carat shows ... dispositi-share)
aggiornamento il mio dispositivo
Here I found View and Risultati globali (words different from two page).
GitHub: https://github.com/carat-project/carat-android/pull/1/commits/5e15629aa0a55fb4aef06e4497d4046ab1b6247e
I found View:
view
This is file.txt modified [View.txt](https://github.com/carat-project/carat-android/files/782619/View.txt)
I found RISULTATI GLOBALI
worldwide statistiche
This is file.txt modified [WorldWide Statistiche.txt](https://github.com/carat-project/carat-android/files/782625/WorldWide.Statistiche.txt)
I didn't find: CRUSCOTTO >> RIEPILOGO (a blank before moves it to page-center)
Title of HOGS is a little LEFT (it is clear when hogs=0 because battery points G) and it shows same message about bugs. In the message there is "bugs". In Italian "bugs" >> "bug" (Italian language accept English words, but we don't use "s". Usualy some do it, but teachers don't accept it). I didn't notice before: "Non hai hogs." >> "Non hai hog". Last character.
page with no hogs
I'm hold on a confirm about "Calibration" >> "Pronto il xx.yy" (Ready on xx.yy with xx=installation day+7 ).
Otherwise I have to think of another, and I do not know how many characters I can use. I consider this  message very important to prevent people (using the first time) doesn't understand that Carat is working. You says in presentation, but here is better.

**Comment by lagerspetz** [comment]
Great that you like this Github way :).
Sto colloquiando con i server is a little long, as you can see the Share button is very close. How about "invio campionamenti".
Also the Updating Hogs ... uses <string name="updating">Aggiornamento</string>, but it could also be just "Ricevente".
What do you think?

I will make the changes for the dashboard, view, global results.
The "ready on <date >" change I will need to discuss with the team.

**Comment by Raffaele74** [comment]
Ok. We have 29 characters long.
Updating status >> Sto inviando i campioni (or "campionamenti" but we used "campioni" in Carat")
Updating Hogs: but now I have 0 hogs. So I dislike "ricevente"; I reiceved ... nothing?
Updating Hogs >> Verifica degli hog (I'm searching for hogs; no "s")
Updating Bugs >> Verifica dei bug
Sto finendo >> Sto elaborando (I don't remember we closed)
x/y Report delle misure ??? Calculate, send or receive? What is x? y? and "/"?
I don't understand well, so I cannot translate well. It seems to me that x/y >> y/x because y from 1 to 113 and when y=113 then x = 1,2,..... 113. I hold on your explanation.
"Ready on": we hold on. During this time (if it isn't short time) we can write "Dammi altro tempo" (See you later). We have 17 characters max.
I found where they are, but they are different from my device. I'm confuse!
 #miniupdating

**Comment by Raffaele74** [comment]
A general consideration. Carat say me "Raffaele, you have no bugs, no hogs". I know that it is false, I have some, Carat said me. Do you thing it is important and we must change in a "perhaps" sentence?
Who don't know well Carat also read "hold on a week", then view Carat stopped first 6h and results after 24h.
Not important, but you are owner of Carat and you must say. If you say yes maybe "hai" >> "ho rilevato" in bold word when hogs/bugs=0. In the other test Carat say "hai" but It seems to say "if there are, in this moment they are well-behavior, so noone".
First time users can think: "only 24h? Happy!" " Nothing? Happy!" or "Nothing? Junk-app!"

Brainstorming (Collaborative ...top down and bottom up)
Action is the less powerful page of Carat: "You maybe perhaps an hog? Live or die!".
Users are of all kinds, some more words can help, but Carat can do much more.
Android-6 (or App Doze and the like) can limit the raid of the Hogs, even those well-behavior-working-hard.
Carat might suggest replacements. Top 200 Hogs is little pier useful: many games and a lot of Asia.
Carat could identify anti-bugs (hogs that works well-behavior in few device) anonymously and ask in the surveys if who have anti-bugs use it and if they use it, how they do.

**Comment by Raffaele74** [comment]
New. (I will update in an hour. about 20.00).
Aggiornato x minuti prima >> Aggiornato da x minuti (or Aggiornato x minuti fà; In Italian prima=before, but you must follow something. User understands, but it is uncorrect)
Have you link to this part of Carta code? So I can view.

Take away the embarrassment. I say everything, then you evaluate.

Just a consideration because I like to understand, and it is a pleasure greater than the need to understand in order to translate. I see Italian Carat working more than English. Just screen is on a rotating wheel appears to me and I always read "just updated". In English Carat I never noticed the wheel and "just updated": I was distracted something changed and now I notice because I started time zero?
Short: Carat work in background? What is maximum time between two updates?

**Comment by lagerspetz** [comment]
The "Just Updated" shows when it has communicated with server recently. If Carat is on screen, it can do this, and you will not see "Updating" when you open it. You can go to Settings and change there "upload samples on the background" to disable background updates. Also you can turn off wifi and mobile data, then you can see "updated x ago"

**Comment by lagerspetz** [comment]
About the time: We run Carat Analysis on our servers every 4 days. For a very unlucky user, it can take a week. For most people, it should take 2-4 days. If users never open Carat, and Carat has no data from their device, it can take much longer than a week. That is why we talk about a week.

**Comment by lagerspetz** [comment]
This is the "updated x m ago" code: https://github.com/carat-project/carat-android/blob/998411e2418bed0e04f8bc270c2f56bd47060145/caratApp/src/main/java/edu/berkeley/cs/amplab/carat/android/MainActivity.java#L712

**Comment by lagerspetz** [comment]
I made the improvements you mentioned. See screenshot: 
screenshot_20170220-133314

**Comment by Raffaele74** [comment]
"Just Updated" Ok, Clear. Thanks.

About the time: 
Do you think all users reading and traslating Carat presentation? I think only few users.
Do you think all users will read Carat Italian presentation? I think no.
So I think give certainty, even false, better then leave them to themselves.
If you say a week in Dashboard, you say in Hogs "Carat don't meet any Hogs here, try next week" is perfect!
Also if Carat find an Hog after one hour. Also for two weeks (try next week).
If you say, right away, as now it is in Italian Hogs page (bold) when zero, "certainly you have no hogs ..." mhm .... maybe.
If you say "ready +7" you can also say "ready +8" it's just for anxious and/or speedy-users, but I thinks that a date (minimum "installed xx.yy) is important. I hold on your opinion about codification "perhaps" (as Carat doesn't meet hogs for the moment, for users that have only one hog: dialer!) in zero Hogs/Bugs page (now twice no bugs, wrong on Hogs page). I don't want give you more job. :-)

"update code": Although understand if then eslse, case, .... I have difficulties. It is hard to distinguish what I should translated and what I not. In this code there are sentences to translate? I will study better, but it seems not.

"I made the improvements you mentioned. See screenshot:" I see change but the same second problem before. RIEPILOGO (EPILOGO centered). Worlwide .... WOW! (also English version?)
riepilogo

**Comment by Raffaele74** [comment]
I do not remember, but maybe it remained to be finalized
xx/yy Report delle misure
I think it is better and still do not understand "Report". Pehaps it is yy/xx (reverse) where xx is report that Carad did and yy is report sended. In this case what is differences between report and sample?

**Comment by Raffaele74** [comment]
Default setting must be "only wifi". Because apps using mobile-data are hogs. Otherwise a warning near permission.

**Comment by Raffaele74** [comment]
**Just to laugh**. In Italy in lottery tickets it says "Try again, you will be more lucky." When Hogs/Bugs =0 we could write "Try again, you will be more unfortunate." :-)

**Comment by Raffaele74** [comment]
Blue ribbon! My first hog! But now I can no longer control hogs = 0. **Also in English version** there is this bug.
no-hogs .
**Annex file txt italian/English**. <<<<<<<<<
[zero Hogs.txt](https://github.com/carat-project/carat-android/files/787655/zero.Hogs.txt)
In annex what I show here down. I changed "You don't have" with "Carat didn't detect" because maybe -1 Hogs withiut user erased.
Link where I find page. 
https://github.com/carat-project/carat-android/pull/1/files
line 123 and more
n.b. Does Carat show "Hogs (Bugs) are ..." in Hogs (Bugs) page when =0? It seems no to me. It is ok for me, but I say because maybe that what I found (and replace in txt) it's not what I search.


 +    <string name="hog_list_message">Hogs sono le app che usualmente usano molta batteria, come si riscontra
 +nella maggior parte dei dispositivi. Terminarle può migliorare la durata della batteria.</string>

 +    <string name="no_hogs_message">Puoi verificare di nuovo fra una settimana.\n\n
 +Carat non ha rilevato app note per il loro consumo intenso. Puoi lasciare a Carat questo compito, o verificare subito nella TOP 200 Hogs.
 +Se Carat rileverà che stai usando un Hog lo indicherà qui. Se tu non ne usi, Carat non ne rileverà, in quanto non incide sulla durata della batteria.
</string>

English (withouth please. I don't know if it is same Italy, but it seems lottery. Also sorry it's no good).
It is not only Google English, but ... verify! :)

 +    <string name="no_hogs_title">No Hogs detected.</string>
 +    <string name="no_hogs_message">You can check back in a week.\n\n
 +Carat didn't detected app notes for their intense consumption. You can leave this task to Carat, or soon check with TOP 200 Hogs.
 +If Carat will detect you using a Hog it will indicate here. If you don't use hogs, Carat doesn't detect, as it doesn't affect the battery life.
</string>

**Comment by Raffaele74** [comment]
Although it is not present but future, I still see that Carat could more. I'm feeling threshold is same for all Hogs. My first Hog belongs to the Google category "video tools". Perhaps Carat is a bit alarmist in this case. I do not know if the Google category can be acquired automatically, but you may leave users possibility of a voluntary contribution. In short, a better distinction between Hogs to Hard workers apps. I like Carat, since it is less alarmist then my Huawei (it cries if app>40mAh).
Even EMUI is very careful on consumption and is very aggressive. But Carat and Emui are not converging almost never.
http://www.androidblog.it/wp-content/uploads/2015/07/Google-Play-Store-Q2-1.png
I am surprised that Facebook does not compare in top 200 hogs .... pheraps it is not fist as hungry, but it is certainly the best known!!
https://www.google.it/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiBxeWR5aHSAhVBXSwKHTInDSMQFggdMAA&url=http%3A%2F%2Fwww.avg.com%2Fcontent%2Fdam%2Fpdfs%2Favg-android-app-performance-report-q4-2014.pdf&usg=AFQjCNHP_XcVpDtTUA48n3_6x1KnLAoOMg&sig2=hup4aeJIxr6KOZ_99B1FGg&bvm=bv.147448319,d.bGg
Probably top hogs with samples<100.000 are less important, but they are a lot. Perhaps these Apps are downloaded by those who have a specific interest and then they use them much more because concerned. With this in mind they are noise in Carat.

**Comment by Raffaele74** [comment]
**! "Measurement error"**.
I'm confuse about "sample" "sample with" "sample whithout" "total sample with (on server)" "sample with on device" .... so ....
Excuse me if I leave the track, but I have a worm. "As there are more sample (total? with? on device?), the **Measurement error** (in minutes) will decrease". But this sentence is what you want to say? More samples (total? on device?) will have, more correct to assume it is normal random, but everyone has their own deviance and moreover I think it might be calculated. Perhaps if deviation is narrow app is a Hog, if deviation is large obviously depends on users (Bug). 
It 's a wrong interpretation?
**If it is not**, we must replaced, "impact" with "medium impact" (English and Italian) and rewrite the help of "Measurement error" (or calculate it differently). It is also strange: Total samples (in the help) never appears in app, but appears "whith" (but you don't write whith) and "without" and perhaps "whith on device" and "whithout on device" making it difficult to understand, because in google play presentation "whith" and "whithout" is "total whith" and "total whithout"..
gaussiana
When I red on my tablet Google Play Services (all users have it) sample whitout 79.468.948 the only think I can thing is impact=impact on device (error 4m, wow!).
Not to show Measurement error is a solution.

**Shortly** I think that to prevent sended message different from received should add on 4 attributes about hogs and bugs: **s** (= worldwide, on servers, global ...), **d** (= only about device), **+** (= with), **-** (= whitout), so I'm shure that **s**-Error is different from **d**-Error and **s**-Samples+ is different from **d**-Samples+. (s-impact or d-impact?)

**Comment by Raffaele74** [comment]
Why 4 hogs and only 2 actions? (on the less hogs?).
4 hogs 2 actions

**Comment by lagerspetz** [comment]
Because Actions show hogs or bugs that are running right now. Hogs show all apps that are installed on your device.

**Comment by lagerspetz** [comment]
Hogs have the same impact on all devices ( +- 4m in the case of Google Play Services).
Bugs have impact that is different for every device, and that is what Carat shows on each device.

However, Carat uses all data from all devices for Hogs, and we are working on making that a time window and specific devices. However, we are a research project, and we are improving the Carat client and service as a side project that is not supported by the University.

**Comment by lagerspetz** [comment]
About centering texts: This is minor tweaking that we may do at some point, but don't consider it urgent.

**Comment by Raffaele74** [comment]
I was not clear, I apologize. 
What I mean is that the interpretation is different from correct message for those unfamiliar with how Carat does.
I like you tell me if it is good to suggest alternative messages (I don't want to do  jobs for you). 
Exemples to be clear:
> adding your answer in "What are the actions"

> expanding "What are these numbers" (which I have not yet understood; it is not important, I realize just because I have to translate correctly).

Center: I notice, I say. Usually I say all, you decide.
So also for 
>"erroneous English and Italian text when Hogs = 0 with .txt attachment"

>"set default only wifi."

**Comment by Raffaele74** [comment]
I try, I do not need the answer, it is just to clarify.
What I do not understand?
Suppose Carat is 100 devices.

Hogs.
Suppose the App is on 80 device and the impact on each consumption is A1, A2, ... A79. 
A0 on my device.
The impact can be:
>A0 and the error is max j-sigma A0
>A0 and error is the maximum difference with An
>A0 and the error is A0-sum (An) / n
>sum (An) / n and the error is j-sigma (this seems to me the answer, because Hog)

Bugs.
Suppose the App is on 80 device and the impact on each consumption is B1, B2, ... B79-k, Ak+1, ... A79. 
A0 on my device. 
Bn<An
The impact can be
>A0 and the error is j-sigma A0 (this seems to me the answer, because Bug)
>A0 and error is j-sigma A0
>A0 and error is the maximum difference with An
>A0 and the error is A0-sum (An) / n
>sum (An) / (n-k) and error is the j-sigma of sum

I think it's because it's not clear if "**total samples**" means total samples (on all devices) or total as sum positive + negative (only my device).

**Comment by Raffaele74** [comment]
4 hogs 2 actions. Now I understand why "live or die"! Thank you very much!

**Comment by Raffaele74** [comment]
**Malfunctions and translation**

Hi. I've Italian version on phone and tablet.
**Phone: I've J-score on 10/3, a lot of time after installation.**

**ALL DEVICE - English (!) and Italian versions** erroneous text when Hogs = 0 with .txt attachment"
[zero.Hogs.txt](https://github.com/carat-project/carat-android/files/854195/zero.Hogs.txt)

Better if  default setting is "only wifi."

**Italian presentation**:
[Carat.txt](https://github.com/carat-project/carat-android/files/824601/Carat.txt)

**Tablet and phone both Android 6**: **Carat kill command doesn't kill HOGS. Manage does it** Manage needs two click, but it is shure. But every threat is also opportunity. Since the data are already reported in Bugs and Hogs you can simplify this frequently used page.
586c3858-0d4b-11e7-9074-357b8aec23b7

I must transalte "Out of" to "Su", but I'm afraid to do.
Here is:
out of

Data about Bugs seems so me exagerate (I used bug-apps only one time)
confronto

**I believe that "error" has a different meaning for you and for users**. If I have an HOG but I don't use it, in my mind error is always 100%. The number of samples is misleading fear.

**Comment by Raffaele74** [comment]
**User experience and emprovement** (I hope)

I want to share my experience of use of Carat. As appropriate, you can deepen for possible development, otherwise okay.

**What do I expected from Carat first time?**

I say with an example. HOG for excellence is Facebook. A lot of people know that uses a lot of power with default settings, it uses less power through proper settings, better to use browser-app that still consume less.
So default-Facebook is a BUG / HOG, it remains HOG with the proper settings and action to do is replace it with a browser-app.

**What do I found?**

> **BUGS**. Ok, my user experience is happy. It fits with my idea of ​​BUG. Sometime impact seems exaggerated to me (flixbzs over 8 hours)
> **ACTION**. Now I understand and is very convenient. But there is a malfunction: on my device does not kill (verified). An hide filter is a good gadget.
> **HOGS**. Here I am not. 
The distance is because Carat measure middle ground between high use and waste. Plus, it measures only a sample and not all apps users have on the device. So it ends up being distracted by fanaticism of gaming apps users. And it is a bad surprise to have a Hog on the device that Carat does not consider (e.g. because user uses rarely). So, often, Carat is different from other sources that give me information about battery drain: AVG and Android 
For these reasons Worlwide ranking is far from that of AVG: it is full of niche apps used by people who are particularly fond of.
My Huawei named hogs an App with battery drain up 20mAh on 6 hours. It say me that Whatsapp, Bluemail, Maps, Prezzi Benzina, Youdrive, are Hogs. Youdrive is so hogs that it cannot work on Huawei devices (Developer ask me an help about this problem and solution is "Youdrive is scandalous for his use of the battery")
Carat silent (better if say e.g. "I don't know well this app")

**What more could be done**.

>**Colors-scale** (Busg and Hogs) It is more interesting a view sorted by day Carat viewed (because apps well-behavior remain) and therefore ranking for battery-drain can be done with colors. (red yellow green icon near orange taste according to the impact).
>**PROCESS**. Very useful, I'd give best evidence. Ability to customize view (through possibility to select show/hide processes - vip). 
>**BUGS**. Allowing a community with an exchange of helps such as Amazon.
>**HOGS**.
I think that Carat must say something about all apps installed on device.
A first list of installed apps can be manually by users. 
Carat does sample, the sample goes to the server, the server processes and returns to user after a lot of days. The user does not know and thinks Carat is strange.
So Carat may have three sections on this page. Active (those that I find in Action), detected by Carat, detected by list of installed apps (manual?).
In Android6 there's consumption for every App, it could use it.
A "K" that allows to discriminate (even by feel) well-behaviour from bad-behaviours seldom used. If (battery impact) / (time I think I usually use app) > "K" then bad else inetensive.
>**WORLDWIDE**. Better access allowing users to filter by number of users, region and some other. Alternatively to filters at least three lists according to the number of users. Increase number of App cataloged. Better extension until it lists AVG hogs.

AVG font: 
[avg-android-app-performance-report-q4-2014.pdf](https://github.com/carat-project/carat-android/files/827418/avg-android-app-performance-report-q4-2014.pdf)

screenshot_2017-03-13-07-29-43
VIPS APP = processes with a filter that hides those which do not wish to view

**Comment by Raffaele74** [comment]
Warning: I'm searching for "Out of" to translate "Su"

**Comment by Raffaele74** [comment]
**A strange case!**

hivoice

**Comment by lagerspetz** [comment]
I have moved your latest comments to https://github.com/carat-project/carat-android/issues/2 and I'm closing this PR now in order to include the translations for our users. Thanks! Feel free to open new issues for things you find, or suggest concrete improvements.

**Pull request merged**
